/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:18dfc356-4857-41ab-b25a-3f6979908786",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uepp8IKLm",
    "aws_user_pools_web_client_id": "3n2ivgdcsmdtmhui2s0nseil1l",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://s5xx3xu6r5bmrlsnavc36mfnwi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wxxpqljnq5cmzibyxt24q7wk7m",
    "aws_user_files_s3_bucket": "mobile965f75596afb4ca68a1e637998665f92180223-monostage",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
