/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:adf2d32c-7c90-456a-bf63-44feec9bbb72",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lp12q7nBP",
    "aws_user_pools_web_client_id": "3pj00p5lqlb3pp603hj04k844j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://rrrthklqsvedlcnslypcmwcxsu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-s7kpk6ycxjazdkkiqoefi76ulq",
    "aws_user_files_s3_bucket": "mobile965f75596afb4ca68a1e637998665f92161112-production",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
