/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:241a5469-2acf-44d4-97c5-0960a2153c61",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PQ86LbV61",
    "aws_user_pools_web_client_id": "3h4oodkd7dca6fhiiu07s3h7gu",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://db6u7rdiqja43jew2mavjks3hu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-knx6ieiz4zaz7mmia5jwwyztvu",
    "aws_user_files_s3_bucket": "mobile-storage142654-mdev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
